services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plant-disease-api-container
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plant-disease-frontend-container
    ports:
      - "5500:80"
    depends_on:
      - backend