[project]
name = "plant-disease-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohamed Abdeldayem", email = "mabdeldayem052@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dvc>=3.67.1",
    "pre-commit>=4.6.2",
]

[project.scripts]
plant-disease-mlops = "plant_disease_mlops:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
